# -*- coding: utf-8 -*-
"""Day1 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DSkPjfXp3RuVLUycbho0QoqK2757s9Ns
"""

x=3
y=2
print(pow(x,y))