# -*- coding: utf-8 -*-
"""Day2 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pgv46L_0d8jXW2T0BHan0rZRfhPJasnH
"""

str=input('Enter the string:')
li=list(str)
print(li)
for i in li:
  print(str.count(i))